import os

top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')
    defines = ['COMPASS_LAB_TEST_INPUT=1'] if os.environ.get('COMPASS_LAB_TEST_INPUT') == '1' else []
    binaries = []
    original = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        ctx.set_group(ctx.env.PLATFORM_NAME)
        ctx.env.append_value('LINKFLAGS', ['-flto', '-Wl,-u,__pbl_app_info'])
        elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_build(source=ctx.path.ant_glob('src/c/*.c'), target=elf,
                      bin_type='app', cflags=['-flto'], defines=defines)
        binaries.append({'platform': platform, 'app_elf': elf})
    ctx.env = original
    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries)
